language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      env: DEPLOY_FILE=libagshttp.so
      addons:
        apt:
          packages:
          - libc6-dev
          - libc6-dev-i386
    - os: osx
      compiler: clang
      env: DEPLOY_FILE=libagshttp.dylib

script:
- pushd agshttp/
- wget https://raw.githubusercontent.com/adventuregamestudio/ags/v.3.4.1.12/Engine/plugin/agsplugin.h
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then clang++ agshttp.cpp -Wall -dynamiclib -o libagshttp.dylib   ; fi
- if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then make    ; fi
- popd

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: VVIxBkBVmDDlA/yX1ZVkwl8OLqJlS53RDmWZF5PeQJ1HRzBunYPdlTC46butYqn6yetziWSJjy2FEPAtqzNCyULaoB/EAi0hqSDqDYt7ZuoQAGizOiC2O5E5N9WJmNo3VyF8qJ7sQ56fQEuLt6C+xPuLXcJU2pTlfEsVXFd4c4YUqJBQZyA9ItQoazZ8S/hWS2/NzK27JrKI/iWi2oyLUG7yi5QkpA1Ts7K6/EUnlXqy5qjlOhylIL4RuNK74Hx3Rd1v16V7E/fs5iKoILgWwGxIcOE/y2gTmIhcYAqm5hxrb5nez37lRqNRf9S+AZ7nN3e5WqaEvLj5ie5Oo/OepXF++MB9cn5z/9g62TS4uTnMmvlE0h0mGEi0SYv0hmg7XHxiJ/p+5ed9ON76ba363pun+4wTS12Pjw04ajzykPZKeBZlNtr3Tu4BxMCfdoEqB1segiaxmTYDYU9VPMw1Xk89OYxG0ZxVfkZS1q8NJtiGFrOvFhjGnQkpMtsvk8JII6VreVShYxKdYt3YeGSffH7VUMCz1ZsmEqq2SBJwFYhSEVQlWTSnG1n9ml7AdamTlwMBRlkd/KmFkR4DEGZ6ciGKhEDi/SxAgLJAnzFnsboG49zENM0Gw2Hq1CaWuoxCorGkbo0DMBDKn7aI86CnFL0mNvN7EoLy47hPcEC1Mvc=
  file: agshttp/$DEPLOY_FILE
  on:
    repo: ericoporto/agshttp
    branch: master
    tags: true
